apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/fe-bmullan/kuard-amd64:blue
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kuard-toplevel
  namespace: default
spec:
  virtualhost:
    fqdn: contour.vinalhaven.info
  includes:
  - name: kuard-proxy
    namespace: default
    conditions:
    - prefix: /
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kuard-proxy
  namespace: default
spec:
  routes:
    - services:
        - name: kuard
          port: 80
      # pathRewritePolicy:
      #   replacePrefix:
      #   - prefix: /team1
      #     replacement: /
